GET http://localhost:5118/api/sets/search?query=AT-AT
Accept: application/json

###

GET http://localhost:5118/api/sets/75313-1
Accept: application/json

###

GET http://localhost:5118/api/sets/not-a-real-set
Accept: application/json